### ISSUE TITLE
doesn't work with "4.07.1"

### ISSUE THREAD

**Issue by mimoo** [dividat/ocaml-semver#5]
Hey!

Great library you have here. I'm trying to use it to parse OCaml's versions, but it fails to parse "4.07.1". I'm not sure if this is valid semver but I assume it could be?

**Comment by knuton** [comment]
This isn't a valid semver version as [leading zeroes are not allowed](https://semver.org/#spec-item-2). I am afraid this library is not suitable for parsing OCaml version numbers, as they don't follow the semver standard.

You might want to take a look at https://opam.ocaml.org/packages/ocaml-version/
